#!/bin/sh
# usage: show-platform      # display "uname -a" and "tool: version" info
#        show-platform -m   # also mail info to ttn

recip='RECIP'

go ()
{
    echo guile-pg: VERSION
    for opt in m s r ; do echo uname-${opt}: `uname -$opt` ; done
    echo autoconf: `autoconf --version | sed -e 's/[^0-9.]*//g;1q'`
    echo automake: `automake --version | sed -e 's/[^0-9.]*//g;1q'`
    echo libtool: `libtool --version | sed 's/([^)]*)//g;s/^[^0-9]*//;1q'`
    echo gcc: `gcc --version`
    echo cc: `cc --version`
    echo psql: `psql --version | sed -e 's/[^0-9.]*//g;1q'`
    echo guile: `guile-config info guileversion`
}

gosexp ()
{
    echo '('
    go | sed 's/^\([-a-z]*\): *\(.*\)/(\1 . "\2")/g'
    echo ')'
}

if [ x"$1" = x-m ] ; then
    tmp="show-platform.$$"
    gosexp > $tmp
    mail -s "show-platform output" $recip < $tmp
    rv=$?
    cat $tmp
    rm $tmp
    [ $rv = 0 ] && echo "(mail successfully sent to $recip)"
else
    go
fi

# show-platform ends here
